Content:
    Beaver:
        root_dir: ${ROOT_DIR}/doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - js/*
            - css/*
            - contrib/**
            - media/**

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    MooseDocs.extensions.navigation:
        name: Beaver
        repo: https://bitbucket.org/trusterresearchgroup/beaver/src/master/
        menu:
            Getting Started:
                Running Beaver: getting_started/RunningBeaver.md
                Input Structure: getting_started/BeaverInputStructure.md
            Documentation:
                Systems: syntax/index.md
            Examples:
                Systems: example/index.md

    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        remove: !include ${MOOSE_DIR}/framework/doc/remove.yml
        includes:
            - include
